### ISSUE TITLE
Chi-Wave Exploit Flagging for PvP

### ISSUE THREAD

**Issue by Heimriel** [Hazor-Hellscream/Project-Hellscream-Info#1037]
Hello

Figured it needed a ticket since it hasn't been officially responded to in discord. 

Chi Wave can be used to force pvp flag non-pvp players, this is a direct game mechanic exploit which I believe should be punishable by your misdemeanor rule but it's w/e if you wish not to take action.

https://www.youtube.com/watch?v=n4HshTQpTJI&feature=youtu.be

I've got another video of it taking place as well. 

Good luck fixing the bug.

**Comment by Nyr97** [comment]
Current behaviour:

Chi wave cannot be cast directly on a PvP flagged player unless you're PvP flagged as well, because the spell tells you that the target is PvP enabled.

If you cast Chi wave on yourself, and then it chooses a PvP flagged player as the bounce hit, it will flag the monk.

If the monk is PvP flagged while casting Chi wave on a PvP disabled player and then it bounces to a PvP flagged player or creature, the primary target (the initial player, not the monk) won't be flagged.

**Comment by Heimriel** [comment]
Hi Nyr

Did you watch the video?

Do I need to post another one to show I'm not flagging.

Let me know I don't mind

Regard

Heimriel

**Comment by Nyr97** [comment]
It was already fixed, just not pushed into live.

**Comment by Heimriel** [comment]
Don't worry about it.

Just close the ticket and be done with it.
