### ISSUE TITLE
Quest- [Qiana Moonshadow:34646]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#264]
Information:
Quest is weekly and Qiana Moonshadow is not at the crash site.

WoWhead link:
https://www.wowhead.com/quest=34646/qiana-moonshadow

**Comment by Firoqt** [comment]
1) Qiana must not be seen by other player's, only by the player who has the quest. Currently Qiana is seen by everyone and when rescued, it's on a 5 minute respawn timer (dead at the location in GM Mode). So need to rework this to make it so that Qiana and Luuka are in a different phase with the player who has the quest.
2) Need to rework the waypoints, it's not blizzlike and need to rework the behaviour. Qiana transforms to a cat mid-path, it should do that at the beginning.
3) Luuka does not despawn after 'saving' Qiana and Luuka and after they start their waypoints.
4) Need to change the 3 Injured Stalker's wandering status in the DB, and make them SetFacingToObject(l_Player)
