### ISSUE TITLE
Spell - Soothing Mist

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#507]
#467 After this fix, channeled spells are fucked. Half the time Soothing Mist just gets interrupted on cast.

Priority:
Critical

**Comment by mhostr18** [comment]
I've discovered something more to this case:
1) Casting Soothing Mist will return "Interrupted"
2) Turn your character (holding Right Click + Move mouse, OR use the arrows to turn character). Now your Soothing Mist works every time.
3) Move your character in any direction using W/S/E/Q. Soothing Mist will now return "Interrupted" again, until you turn your character like in step 2.

The bug seems to reappear anytime you move, and you have to turn, in order to fix it every time.
Hope this discovery somehow helps.

**Comment by Saesuri** [comment]
Fixed.
